---
services:
  - name: "NetworkManager.service"
    mandatory: true
    enabled: true

  - name: "systemd-resolved.service"
    mandatory: true
    enabled: true

  - name: "systemd-networkd.service"
    mandatory: true
    enabled: false

  - name: "systemd-networkd-wait-online.service"
    mandatory: false
    enabled: false
